
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<title>RakNet: Class List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<!-- Generated by Doxygen 1.7.1 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="main.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li><a href="modules.html"><span>Modules</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="classes.html"><span>Class&nbsp;Index</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Class List</h1>  </div>
</div>
<div class="contents">
Here are the classes, structs, unions and interfaces with brief descriptions:<table>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_client_1_1_addr_and_guid.html">NatPunchthroughClient::AddrAndGuid</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_address_or_g_u_i_d.html">AddressOrGUID</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_autopatcher_repository_interface.html">AutopatcherRepositoryInterface</a></td><td class="indexvalue">An interface used by AutopatcherServer to get the data necessary to run an autopatcher. This is up to you to implement for custom repository solutions </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_auto_r_p_c.html">RakNet::AutoRPC</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_replica2_1_1_auto_serialize_event.html">RakNet::Replica2::AutoSerializeEvent</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_a_v_l_balanced_binary_search_tree.html">DataStructures::AVLBalancedBinarySearchTree&lt; BinarySearchTreeType &gt;</a></td><td class="indexvalue">An <a class="el" href="class_data_structures_1_1_a_v_l_balanced_binary_search_tree.html" title="An AVLBalancedBinarySearchTree is a binary tree that is always balanced.">AVLBalancedBinarySearchTree</a> is a binary tree that is always balanced </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_h_t_t_p_connection_1_1_bad_response.html">HTTPConnection::BadResponse</a></td><td class="indexvalue">Encapsulates a raw HTTP response and response code </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_ban_struct.html">RakPeer::BanStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_binary_search_tree.html">DataStructures::BinarySearchTree&lt; BinarySearchTreeType &gt;</a></td><td class="indexvalue">A binary search tree and an AVL balanced binary search tree </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_bit_stream.html">RakNet::BitStream</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_b_plus_tree.html">DataStructures::BPlusTree&lt; KeyType, DataType, order &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_b_p_s_tracker.html">BPSTracker</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_buffered_command_struct.html">RakPeer::BufferedCommandStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_byte_pool.html">DataStructures::BytePool</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_byte_queue.html">DataStructures::ByteQueue</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_gen_r_p_c_1_1_call_params.html">GenRPC::CallParams</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="unioncat_float32.html">catFloat32</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_c_c_rak_net_u_d_t.html">RakNet::CCRakNetUDT</a></td><td class="indexvalue">Encapsulates UDT congestion control, as used by <a class="el" href="namespace_rak_net.html" title="Forward declaration.">RakNet</a> Requirements: </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_table_1_1_cell.html">DataStructures::Table::Cell</a></td><td class="indexvalue">Holds the actual data in the table </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_variable_delta_serializer_1_1_changed_variables_list.html">RakNet::VariableDeltaSerializer::ChangedVariablesList</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_check_sum.html">CheckSum</a></td><td class="indexvalue">Generates and validates checksums </td></tr>
  <tr><td class="indexkey"><a class="el" href="structcipher_instance.html">cipherInstance</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_circular_linked_list.html">DataStructures::CircularLinkedList&lt; CircularLinkedListType &gt;</a></td><td class="indexvalue">(Circular) Linked <a class="el" href="class_data_structures_1_1_list.html" title="Array based implementation of a list.">List</a> ADT (Doubly Linked Pointer to Node Style) - </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_table_1_1_column_descriptor.html">DataStructures::Table::ColumnDescriptor</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_command_parser_interface.html">CommandParserInterface</a></td><td class="indexvalue">The interface used by command parsers </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_replica_manager_1_1_command_struct.html">ReplicaManager::CommandStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_connection___r_m2.html">RakNet::Connection_RM2</a></td><td class="indexvalue">This class represents a connection between two instances of <a class="el" href="class_rak_net_1_1_replica_manager2.html" title="A management system for your game objects and players to make serialization, scoping, and object creation and destruction easier.">ReplicaManager2</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_connection___r_m2_factory.html">RakNet::Connection_RM2Factory</a></td><td class="indexvalue">Implement this factory class to return instances of your <a class="el" href="class_rak_net_1_1_connection___r_m2.html" title="This class represents a connection between two instances of ReplicaManager2.">Connection_RM2</a> derived object. This is used as a class factory and exposes functionality related to the connection and the system </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_connection___r_m3.html">RakNet::Connection_RM3</a></td><td class="indexvalue">Each remote system is represented by <a class="el" href="class_rak_net_1_1_connection___r_m3.html" title="Each remote system is represented by Connection_RM3. Used to allocate Replica3 and track which instan...">Connection_RM3</a>. Used to allocate <a class="el" href="class_rak_net_1_1_replica3.html" title="Base class for your replicated objects for the ReplicaManager3 system.">Replica3</a> and track which instances have been allocated </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_server_1_1_connection_attempt.html">NatPunchthroughServer::ConnectionAttempt</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_connection_graph.html">ConnectionGraph</a></td><td class="indexvalue">A connection graph. Each peer will know about all other peers </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_connection_graph2.html">ConnectionGraph2</a></td><td class="indexvalue">A one hop connection graph </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_router2_1_1_connection_request_system.html">RakNet::Router2::ConnectionRequestSystem</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_router2_1_1_connnect_request.html">RakNet::Router2::ConnnectRequest</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_console_server.html">ConsoleServer</a></td><td class="indexvalue">The main entry point for the server portion of your remote console application support </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_c_s_h_a1.html">CSHA1</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_database_cell_update.html">DatabaseCellUpdate</a></td><td class="indexvalue">The value to write to a cell in a remote database </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_database_filter.html">DatabaseFilter</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_lightweight_database_server_1_1_database_table.html">LightweightDatabaseServer::DatabaseTable</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_block_encryptor.html">DataBlockEncryptor</a></td><td class="indexvalue">Encrypts and decrypts data blocks </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_compressor.html">DataCompressor</a></td><td class="indexvalue">Does compression on a block of data. Not very good compression, but it's small and fast so is something you can compute at runtime </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_datagram_header_format.html">DatagramHeaderFormat</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_d_d_t_callback.html">DDTCallback</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_variable_delta_serializer_1_1_deserialization_context.html">RakNet::VariableDeltaSerializer::DeserializationContext</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_deserialize_parameters.html">RakNet::DeserializeParameters</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_directory_delta_transfer.html">DirectoryDeltaTransfer</a></td><td class="indexvalue">Simple class to send changes between directories. In essence, a simple autopatcher that can be used for transmitting levels, skins, etc </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_email_sender.html">EmailSender</a></td><td class="indexvalue">Rudimentary class to send email from code </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_fully_connected_mesh2_1_1_f_c_m2_participant.html">FullyConnectedMesh2::FCM2Participant</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_file_list.html">FileList</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_node.html">FileListNode</a></td><td class="indexvalue">Represents once instance of a file </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_node_context.html">FileListNodeContext</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_file_list_progress.html">FileListProgress</a></td><td class="indexvalue">Callback interface set with <a class="el" href="class_file_list.html#a7fc5c8188d260d019e0e84bc5a6aceff" title="Set a callback to get progress reports about what this class does.">FileList::SetCallback()</a> in case you want progress notifications when <a class="el" href="class_file_list.html#ad0a790b553a237a79f372a4a3e4559f1" title="Add all the files at a given directory.">FileList::AddFilesFromDirectory()</a> is called </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_receiver.html">FileListReceiver</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_file_list_transfer.html">FileListTransfer</a></td><td class="indexvalue">A plugin to provide a simple way to compress and incrementally send the files in the <a class="el" href="class_file_list.html">FileList</a> structure </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_file_list_transfer_c_b_interface.html">FileListTransferCBInterface</a></td><td class="indexvalue">Used by <a class="el" href="class_file_list_transfer.html" title="A plugin to provide a simple way to compress and incrementally send the files in the FileList structu...">FileListTransfer</a> plugin as a callback for when we get a file </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_transfer_c_b_interface_1_1_file_progress_struct.html">FileListTransferCBInterface::FileProgressStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_transfer_1_1_file_to_push.html">FileListTransfer::FileToPush</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_transfer_1_1_file_to_push_recipient.html">FileListTransfer::FileToPushRecipient</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_filtered_system.html">FilteredSystem</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_table_1_1_filter_query.html">DataStructures::Table::FilterQuery</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_filter_set.html">FilterSet</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_f_l_p___printf.html">FLP_Printf</a></td><td class="indexvalue">Implementation of <a class="el" href="class_file_list_progress.html" title="Callback interface set with FileList::SetCallback() in case you want progress notifications when File...">FileListProgress</a> to use RAKNET_DEBUG_PRINTF </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_f_l_r___memory_block.html">FLR_MemoryBlock</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_router2_1_1_forwarded_connection.html">RakNet::Router2::ForwardedConnection</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_forwarder_1_1_forward_entry.html">RakNet::UDPForwarder::ForwardEntry</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_coordinator_1_1_forwarding_request.html">RakNet::UDPProxyCoordinator::ForwardingRequest</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_fully_connected_mesh.html">FullyConnectedMesh</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_fully_connected_mesh2.html">FullyConnectedMesh2</a></td><td class="indexvalue">Fully connected mesh plugin, revision 2 </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_function_thread.html">RakNet::FunctionThread</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_function_thread_dependent_class.html">RakNet::FunctionThreadDependentClass</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_functor.html">RakNet::Functor</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_function_thread_1_1_functor_and_context.html">RakNet::FunctionThread::FunctorAndContext</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_grid_sectorizer.html">GridSectorizer</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_heap.html">DataStructures::Heap&lt; weight_type, data_type, isMaxHeap &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_ordered_channel_heap_1_1_heap_channel_and_data.html">DataStructures::OrderedChannelHeap&lt; channel_key_type, heap_data_type, channel_key_comparison_func &gt;::HeapChannelAndData</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_heap_1_1_heap_node.html">DataStructures::Heap&lt; weight_type, data_type, isMaxHeap &gt;::HeapNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_h_t_t_p_connection.html">HTTPConnection</a></td><td class="indexvalue">Use <a class="el" href="class_h_t_t_p_connection.html" title="Use HTTPConnection to communicate with a web server.">HTTPConnection</a> to communicate with a web server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_huffman_encoding_tree.html">HuffmanEncodingTree</a></td><td class="indexvalue">This generates special cases of the huffman encoding tree using 8 bit keys with the additional condition that unused combinations of 8 bits are treated as a frequency of 1 </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_huffman_encoding_tree_factory.html">HuffmanEncodingTreeFactory</a></td><td class="indexvalue">Creates instances of the class <a class="el" href="class_huffman_encoding_tree.html" title="This generates special cases of the huffman encoding tree using 8 bit keys with the additional condit...">HuffmanEncodingTree</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_huffman_encoding_tree_node.html">HuffmanEncodingTreeNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_incremental_read_interface.html">IncrementalReadInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_variadic_s_q_l_parser_1_1_index_and_type.html">VariadicSQLParser::IndexAndType</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_inline_functor.html">InlineFunctor</a></td><td class="indexvalue">A base class to derive functors from for the <a class="el" href="class_inline_functor_processor.html" title="A base class that will allow you to call YieldOnFunctor() from within a function, and continue with t...">InlineFunctorProcessor</a> system </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_inline_functor_processor.html">InlineFunctorProcessor</a></td><td class="indexvalue">A base class that will allow you to call <a class="el" href="class_inline_functor_processor.html#aa8744f36abcd566d409b77e880090f63">YieldOnFunctor()</a> from within a function, and continue with that function when the asynchronous processing has completed </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_internal_packet.html">InternalPacket</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_internal_packet_fixed_size_transmission_header.html">InternalPacketFixedSizeTransmissionHeader</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_internal_packet_ref_counted_data.html">InternalPacketRefCountedData</a></td><td class="indexvalue">Used in <a class="el" href="struct_internal_packet.html">InternalPacket</a> when pointing to sharedDataBlock, rather than allocating itself </td></tr>
  <tr><td class="indexkey"><a class="el" href="structkey_instance.html">keyInstance</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_last_serialization_result.html">RakNet::LastSerializationResult</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_last_serialization_result_b_s.html">RakNet::LastSerializationResultBS</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_lightweight_database_client.html">LightweightDatabaseClient</a></td><td class="indexvalue">The client interface to the simple database included with <a class="el" href="namespace_rak_net.html" title="Forward declaration.">RakNet</a>, useful for a server browser or a lobby server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_lightweight_database_server.html">LightweightDatabaseServer</a></td><td class="indexvalue">A simple flat database included with <a class="el" href="namespace_rak_net.html" title="Forward declaration.">RakNet</a>, useful for a server browser or a lobby server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_linked_list.html">DataStructures::LinkedList&lt; LinkedListType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_list.html">DataStructures::List&lt; list_type &gt;</a></td><td class="indexvalue">Array based implementation of a list </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_auto_r_p_c_1_1_local_r_p_c_function.html">RakNet::AutoRPC::LocalRPCFunction</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_log_command_parser.html">LogCommandParser</a></td><td class="indexvalue">Adds the ability to send logging output to a remote console </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_map.html">DataStructures::Map&lt; key_type, data_type, key_comparison_func &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_map_1_1_map_node.html">DataStructures::Map&lt; key_type, data_type, key_comparison_func &gt;::MapNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_memory_pool.html">DataStructures::MemoryPool&lt; MemoryBlockType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_memory_pool_1_1_memory_with_page.html">DataStructures::MemoryPool&lt; MemoryBlockType &gt;::MemoryWithPage</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_message_filter.html">MessageFilter</a></td><td class="indexvalue">Assigns systems to FilterSets. Each <a class="el" href="struct_filter_set.html">FilterSet</a> limits what kinds of messages are allowed </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_router2_1_1_mini_punch_request.html">RakNet::Router2::MiniPunchRequest</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_m_l_key_ref.html">DataStructures::MLKeyRef&lt; templateType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_multilist.html">DataStructures::Multilist&lt; _MultilistType, _DataType, _KeyType, _IndexType &gt;</a></td><td class="indexvalue">The multilist, representing an abstract data type that generally holds lists </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_nat_type_detection_server_1_1_n_a_t_detection_attempt.html">RakNet::NatTypeDetectionServer::NATDetectionAttempt</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_nat_punchthrough_client.html">NatPunchthroughClient</a></td><td class="indexvalue">Client code for NATPunchthrough </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_debug_interface.html">NatPunchthroughDebugInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_debug_interface___packet_logger.html">NatPunchthroughDebugInterface_PacketLogger</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_debug_interface___printf.html">NatPunchthroughDebugInterface_Printf</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_nat_punchthrough_server.html">NatPunchthroughServer</a></td><td class="indexvalue">Server code for NATPunchthrough </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_server_debug_interface.html">NatPunchthroughServerDebugInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_server_debug_interface___packet_logger.html">NatPunchthroughServerDebugInterface_PacketLogger</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_server_debug_interface___printf.html">NatPunchthroughServerDebugInterface_Printf</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_nat_type_detection_client.html">RakNet::NatTypeDetectionClient</a></td><td class="indexvalue">Client code for NatTypeDetection </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_nat_type_detection_server.html">RakNet::NatTypeDetectionServer</a></td><td class="indexvalue">Server code for NatTypeDetection </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_network_i_d.html">NetworkID</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_network_i_d_manager.html">NetworkIDManager</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_network_i_d_node.html">NetworkIDNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_network_i_d_object.html">NetworkIDObject</a></td><td class="indexvalue">Unique shared ids for each object instance </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_circular_linked_list_1_1node.html">DataStructures::CircularLinkedList&lt; CircularLinkedListType &gt;::node</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_binary_search_tree_1_1node.html">DataStructures::BinarySearchTree&lt; BinarySearchTreeType &gt;::node</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_string_keyed_hash_1_1_node.html">DataStructures::StringKeyedHash&lt; data_type, HASH_SIZE &gt;::Node</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_weighted_graph_1_1_node_and_parent.html">DataStructures::WeightedGraph&lt; node_type, weight_type, allow_unlinkedNodes &gt;::NodeAndParent</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_file_list_transfer_c_b_interface_1_1_on_file_struct.html">FileListTransferCBInterface::OnFileStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_ordered_channel_heap.html">DataStructures::OrderedChannelHeap&lt; channel_key_type, heap_data_type, channel_key_comparison_func &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_ordered_list.html">DataStructures::OrderedList&lt; key_type, data_type, default_comparison_function &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_h_t_t_p_connection_1_1_outgoing_post.html">HTTPConnection::OutgoingPost</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_packet.html">Packet</a></td><td class="indexvalue">This represents a user message from another system </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_packet_console_logger.html">PacketConsoleLogger</a></td><td class="indexvalue">Packetlogger that logs to a remote command console </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_packet_file_logger.html">PacketFileLogger</a></td><td class="indexvalue">Packetlogger that outputs to a file </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_packet_followed_by_data.html">PacketFollowedByData</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_packetized_t_c_p.html">PacketizedTCP</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_packet_logger.html">PacketLogger</a></td><td class="indexvalue">Writes incoming and outgoing messages to the screen. This will write all incoming and outgoing messages to the console window, or to a file if you override it and give it this functionality </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_packet_output_window_logger.html">PacketOutputWindowLogger</a></td><td class="indexvalue">Packetlogger that outputs to the output window in the debugger. Windows only </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_memory_pool_1_1_page.html">DataStructures::MemoryPool&lt; MemoryBlockType &gt;::Page</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_page.html">DataStructures::Page&lt; KeyType, DataType, order &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_replica_manager_1_1_participant_struct.html">ReplicaManager::ParticipantStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_ping_and_clock_differential.html">RakPeer::PingAndClockDifferential</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_client_1_1_ping_server_group.html">RakNet::UDPProxyClient::PingServerGroup</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_plugin_interface2.html">PluginInterface2</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_p_r_o.html">RakNet::PRO</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_punchthrough_configuration.html">PunchthroughConfiguration</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_queue.html">DataStructures::Queue&lt; queue_type &gt;</a></td><td class="indexvalue">A queue implemented as an array with a read and write index </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_ordered_channel_heap_1_1_queue_and_weight.html">DataStructures::OrderedChannelHeap&lt; channel_key_type, heap_data_type, channel_key_comparison_func &gt;::QueueAndWeight</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_queue_linked_list.html">DataStructures::QueueLinkedList&lt; QueueType &gt;</a></td><td class="indexvalue">A queue implemented using a linked list. Rarely used </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_command_parser.html">RakNetCommandParser</a></td><td class="indexvalue">This allows a console client to call most of the functions in <a class="el" href="class_rak_peer.html" title="Main interface for network communications.">RakPeer</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_g_u_i_d.html">RakNetGUID</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_random.html">RakNetRandom</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_smart_ptr.html">RakNetSmartPtr&lt; T &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_socket.html">RakNetSocket</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_statistics.html">RakNetStatistics</a></td><td class="indexvalue">Network Statisics Usage </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_transport.html">RakNetTransport</a></td><td class="indexvalue">Use <a class="el" href="class_rak_net_transport.html" title="Use RakNetTransport if you need a secure connection between the client and the console server...">RakNetTransport</a> if you need a secure connection between the client and the console server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_transport2.html">RakNetTransport2</a></td><td class="indexvalue">Use <a class="el" href="class_rak_net_transport.html" title="Use RakNetTransport if you need a secure connection between the client and the console server...">RakNetTransport</a> if you need a secure connection between the client and the console server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_transport_command_parser.html">RakNetTransportCommandParser</a></td><td class="indexvalue"><a class="el" href="class_rak_net_transport.html" title="Use RakNetTransport if you need a secure connection between the client and the console server...">RakNetTransport</a> has its own command parser to enable remote users to change the command console's password </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_network_factory.html">RakNetworkFactory</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_peer.html">RakPeer</a></td><td class="indexvalue">Main interface for network communications </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_and_index.html">RakPeerAndIndex</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_peer_interface.html">RakPeerInterface</a></td><td class="indexvalue">The main interface for network communications </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_rak_string.html">RakNet::RakString</a></td><td class="indexvalue">String class </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_string_cleanup.html">RakStringCleanup</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_rak_thread.html">RakNet::RakThread</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_range_list.html">DataStructures::RangeList&lt; range_type &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_range_node.html">DataStructures::RangeNode&lt; range_type &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_ready_event.html">ReadyEvent</a></td><td class="indexvalue">Peer to peer synchronized ready and unready events </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_ready_event_1_1_ready_event_node.html">ReadyEvent::ReadyEventNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_receive_construction_interface.html">ReceiveConstructionInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_replica_manager_1_1_received_command.html">ReplicaManager::ReceivedCommand</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_receive_download_complete_interface.html">ReceiveDownloadCompleteInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_recv_from_struct.html">RakPeer::RecvFromStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_ref_counted_obj.html">RefCountedObj</a></td><td class="indexvalue">World's simplest class :) </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_reference_counter.html">ReferenceCounter</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_registered_command.html">RegisteredCommand</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_replica_manager_1_1_registered_replica.html">ReplicaManager::RegisteredReplica</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_reliability_layer.html">ReliabilityLayer</a></td><td class="indexvalue">Datagram reliable, ordered, unordered and sequenced sends. Flow control. Message splitting, reassembly, and coalescence </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_remote_client.html">RemoteClient</a></td><td class="indexvalue">Stores information about a remote client </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_replica_manager_1_1_remote_object.html">ReplicaManager::RemoteObject</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_auto_r_p_c_1_1_remote_r_p_c_function.html">RakNet::AutoRPC::RemoteRPCFunction</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_ready_event_1_1_remote_system.html">ReadyEvent::RemoteSystem</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_connection_graph2_1_1_remote_system.html">ConnectionGraph2::RemoteSystem</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_remote_system_index.html">RemoteSystemIndex</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_remote_system_struct.html">RakPeer::RemoteSystemStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_variable_delta_serializer_1_1_remote_system_variable_history.html">RakNet::VariableDeltaSerializer::RemoteSystemVariableHistory</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_replica.html">Replica</a></td><td class="indexvalue">The interface to derive your game's networked classes from </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_replica2.html">RakNet::Replica2</a></td><td class="indexvalue">Base class for game objects that use the <a class="el" href="class_rak_net_1_1_replica_manager2.html" title="A management system for your game objects and players to make serialization, scoping, and object creation and destruction easier.">ReplicaManager2</a> system </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_replica3.html">RakNet::Replica3</a></td><td class="indexvalue">Base class for your replicated objects for the <a class="el" href="class_rak_net_1_1_replica_manager3.html" title="System to help automate game object construction, destruction, and serialization.">ReplicaManager3</a> system </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_replica_manager.html">ReplicaManager</a></td><td class="indexvalue">A management system for your game objects and players to make serialization, scoping, and object creation and destruction easier </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_replica_manager2.html">RakNet::ReplicaManager2</a></td><td class="indexvalue">A management system for your game objects and players to make serialization, scoping, and object creation and destruction easier </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_replica_manager3.html">RakNet::ReplicaManager3</a></td><td class="indexvalue">System to help automate game object construction, destruction, and serialization </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_requested_connection_struct.html">RakPeer::RequestedConnectionStruct</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_b_plus_tree_1_1_return_action.html">DataStructures::BPlusTree&lt; KeyType, DataType, order &gt;::ReturnAction</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_router.html">Router</a></td><td class="indexvalue">Used to route messages between peers </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_router2.html">RakNet::Router2</a></td><td class="indexvalue">Class interface for the <a class="el" href="class_rak_net_1_1_router2.html" title="Class interface for the Router2 system.">Router2</a> system </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_router2_debug_interface.html">RakNet::Router2DebugInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_router_interface.html">RouterInterface</a></td><td class="indexvalue">On failed directed sends, <a class="el" href="namespace_rak_net.html" title="Forward declaration.">RakNet</a> can call an alternative send function to use </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_table_1_1_row.html">DataStructures::Table::Row</a></td><td class="indexvalue">Stores the list of cells for this row, and a special flag used for internal sorting </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_r_p_c4_plugin.html">RakNet::RPC4Plugin</a></td><td class="indexvalue">The <a class="el" href="class_rak_net_1_1_r_p_c4_plugin.html" title="The RPC4Plugin plugin is just an association between a C function pointer and a string.">RPC4Plugin</a> plugin is just an association between a C function pointer and a string </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_auto_r_p_c_1_1_r_p_c_identifier.html">RakNet::AutoRPC::RPCIdentifier</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_r_p_c_map.html">RPCMap</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_r_p_c_node.html">RPCNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_r_p_c_parameters.html">RPCParameters</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_r_s_a_crypt.html">RSACrypt</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_send_download_complete_interface.html">SendDownloadCompleteInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_coordinator_1_1_sender_and_target_address.html">RakNet::UDPProxyCoordinator::SenderAndTargetAddress</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_client_1_1_sender_and_target_address.html">RakNet::UDPProxyClient::SenderAndTargetAddress</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_client_1_1_send_ping.html">NatPunchthroughClient::SendPing</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_variable_delta_serializer_1_1_serialization_context.html">RakNet::VariableDeltaSerializer::SerializationContext</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_serialization_context.html">RakNet::SerializationContext</a></td><td class="indexvalue">Contextual information about serialization, passed to some functions in <a class="el" href="class_rak_net_1_1_replica2.html" title="Base class for game objects that use the ReplicaManager2 system.">Replica2</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_serialize_parameters.html">RakNet::SerializeParameters</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_client_1_1_server_with_ping.html">RakNet::UDPProxyClient::ServerWithPing</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_coordinator_1_1_server_with_ping.html">RakNet::UDPProxyCoordinator::ServerWithPing</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="union_c_s_h_a1_1_1_s_h_a1___w_o_r_k_s_p_a_c_e___b_l_o_c_k.html">CSHA1::SHA1_WORKSPACE_BLOCK</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_rak_string_1_1_shared_string.html">RakNet::RakString::SharedString</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_signaled_event.html">SignaledEvent</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_simple_mutex.html">SimpleMutex</a></td><td class="indexvalue">An easy to use mutex </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_single_producer_consumer.html">DataStructures::SingleProducerConsumer&lt; SingleProducerConsumerType &gt;</a></td><td class="indexvalue">A single producer consumer implementation without critical sections </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_socket_descriptor.html">SocketDescriptor</a></td><td class="indexvalue">Describes the local socket to use for <a class="el" href="class_rak_peer.html#a1fbd8608cf1ead14250b293cc6eb9a85" title="Starts the network threads and opens the listen port.">RakPeer::Startup</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_socket_layer.html">SocketLayer</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_socket_layer_override.html">SocketLayerOverride</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_peer_1_1_socket_query_output.html">RakPeer::SocketQueryOutput</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_table_1_1_sort_query.html">DataStructures::Table::SortQuery</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_split_packet_channel.html">SplitPacketChannel</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_forwarder_1_1_src_and_dest.html">RakNet::UDPForwarder::SrcAndDest</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_str_and_bool.html">StrAndBool</a></td><td class="indexvalue">The string plus a bool telling us if this string was copied or not </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_string_compressor.html">StringCompressor</a></td><td class="indexvalue">Writes and reads strings to and from bitstreams </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_string_keyed_hash.html">DataStructures::StringKeyedHash&lt; data_type, HASH_SIZE &gt;</a></td><td class="indexvalue">Using a string as a identifier for a node, store an allocated pointer to that node </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_data_structures_1_1_string_keyed_hash_index.html">DataStructures::StringKeyedHashIndex</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_string_table.html">RakNet::StringTable</a></td><td class="indexvalue">Writes a string index, instead of the whole string </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_system_address.html">SystemAddress</a></td><td class="indexvalue">Network address for a system </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_log_command_parser_1_1_system_address_and_channel.html">LogCommandParser::SystemAddressAndChannel</a></td><td class="indexvalue">One of these structures is created per player </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_connection_graph_1_1_system_address_and_group_id.html">ConnectionGraph::SystemAddressAndGroupId</a></td><td class="indexvalue">A node in the connection graph </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_connection_graph2_1_1_system_address_and_guid.html">ConnectionGraph2::SystemAddressAndGuid</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_system_address_list.html">SystemAddressList</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_table.html">DataStructures::Table</a></td><td class="indexvalue">Holds a set of columns, a set of rows, and rows times columns cells </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_table_serializer.html">TableSerializer</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_t_c_p_interface.html">TCPInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_team_balancer.html">RakNet::TeamBalancer</a></td><td class="indexvalue">Set and network team selection (supports peer to peer or client/server) </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_team_balancer_1_1_team_member.html">RakNet::TeamBalancer::TeamMember</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_telnet_transport_1_1_telnet_client.html">TelnetTransport::TelnetClient</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_telnet_transport.html">TelnetTransport</a></td><td class="indexvalue">Use <a class="el" href="class_telnet_transport.html" title="Use TelnetTransport to easily allow windows telnet to connect to your ConsoleServer.">TelnetTransport</a> to easily allow windows telnet to connect to your <a class="el" href="class_console_server.html" title="The main entry point for the server portion of your remote console application support.">ConsoleServer</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_t_c_p_interface_1_1_this_ptr_plus_sys_addr.html">TCPInterface::ThisPtrPlusSysAddr</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_thread_data_interface.html">ThreadDataInterface</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_forwarder_1_1_thread_operation.html">RakNet::UDPForwarder::ThreadOperation</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_thread_pool.html">ThreadPool&lt; InputType, OutputType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_threadsafe_allocating_queue.html">DataStructures::ThreadsafeAllocatingQueue&lt; structureType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_threadsafe_packet_logger.html">ThreadsafePacketLogger</a></td><td class="indexvalue">Same as <a class="el" href="class_packet_logger.html" title="Writes incoming and outgoing messages to the screen. This will write all incoming and outgoing messag...">PacketLogger</a>, but writes output in the user thread </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_b_p_s_tracker_1_1_time_and_value2.html">BPSTracker::TimeAndValue2</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_transport_interface.html">TransportInterface</a></td><td class="indexvalue">Defines an interface that is used to send and receive null-terminated strings </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_tree.html">DataStructures::Tree&lt; TreeType &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_type_mapping.html">TypeMapping</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="structu128.html">u128</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_u_d_p_forwarder.html">RakNet::UDPForwarder</a></td><td class="indexvalue">Forwards UDP datagrams. Independent of RakNet's protocol </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_u_d_p_proxy_client.html">RakNet::UDPProxyClient</a></td><td class="indexvalue">Communicates with <a class="el" href="class_rak_net_1_1_u_d_p_proxy_coordinator.html" title="Middleman between UDPProxyServer and UDPProxyClient, maintaining a list of UDPProxyServer, and managing state for clients to find an available forwarding server.">UDPProxyCoordinator</a>, in order to find a <a class="el" href="class_rak_net_1_1_u_d_p_proxy_server.html" title="UDPProxyServer to control our instance of UDPForwarder.">UDPProxyServer</a> to forward our datagrams </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_client_result_handler.html">RakNet::UDPProxyClientResultHandler</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_u_d_p_proxy_coordinator.html">RakNet::UDPProxyCoordinator</a></td><td class="indexvalue">Middleman between <a class="el" href="class_rak_net_1_1_u_d_p_proxy_server.html" title="UDPProxyServer to control our instance of UDPForwarder.">UDPProxyServer</a> and <a class="el" href="class_rak_net_1_1_u_d_p_proxy_client.html" title="Communicates with UDPProxyCoordinator, in order to find a UDPProxyServer to forward our datagrams...">UDPProxyClient</a>, maintaining a list of <a class="el" href="class_rak_net_1_1_u_d_p_proxy_server.html" title="UDPProxyServer to control our instance of UDPForwarder.">UDPProxyServer</a>, and managing state for clients to find an available forwarding server </td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_u_d_p_proxy_server.html">RakNet::UDPProxyServer</a></td><td class="indexvalue"><a class="el" href="class_rak_net_1_1_u_d_p_proxy_server.html" title="UDPProxyServer to control our instance of UDPForwarder.">UDPProxyServer</a> to control our instance of <a class="el" href="class_rak_net_1_1_u_d_p_forwarder.html" title="Forwards UDP datagrams. Independent of RakNet&#39;s protocol.">UDPForwarder</a> </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_u_d_p_proxy_server_result_handler.html">RakNet::UDPProxyServerResultHandler</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="structuint24__t.html">uint24_t</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_nat_punchthrough_server_1_1_user.html">NatPunchthroughServer::User</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_variable_delta_serializer.html">RakNet::VariableDeltaSerializer</a></td><td class="indexvalue">Class to compare memory values of variables in a current state to a prior state Results of the comparisons will be written to a bitStream, such that only changed variables get written<br/>
 Can be used with <a class="el" href="class_rak_net_1_1_replica_manager3.html" title="System to help automate game object construction, destruction, and serialization.">ReplicaManager3</a> to Serialize a <a class="el" href="class_rak_net_1_1_replica3.html" title="Base class for your replicated objects for the ReplicaManager3 system.">Replica3</a> per-variable, rather than comparing the entire object against itself<br/>
 Usage:<br/>
 BR&gt; 1. Call <a class="el" href="class_rak_net_1_1_variable_delta_serializer.html#a27e535da230f0bae45cda69fe73688fd" title="Call before doing one or more SerializeVariable calls when the data will be sent UNRELIABLE_WITH_ACK_...">BeginUnreliableAckedSerialize()</a>, <a class="el" href="class_rak_net_1_1_variable_delta_serializer.html#aa6fe275e35d38525bbb1b6034d811377" title="Call before doing one or more SerializeVariable calls for data that may be sent differently to every ...">BeginUniqueSerialize()</a>, or <a class="el" href="class_rak_net_1_1_variable_delta_serializer.html#ae60fb932dd24b2292b193f1b53d3f590" title="Call before doing one or more SerializeVariable calls for data that is sent with the same value to ev...">BeginIdenticalSerialize()</a>. In the case of <a class="el" href="class_rak_net_1_1_replica3.html" title="Base class for your replicated objects for the ReplicaManager3 system.">Replica3</a>, this would be in the Serialize() call<br/>
 2. For each variable of the type in step 1, call Serialize(). The same variables must be serialized every tick()<br/>
 3. Call <a class="el" href="class_rak_net_1_1_variable_delta_serializer.html#a6a62baf07ffe9e70c4c1804bf5040cf5" title="Call after BeginUnreliableAckedSerialize(), BeginUniqueSerialize(), or BeginIdenticalSerialize(), then after calling SerializeVariable() one or more times.">EndSerialize()</a><br/>
 4. Repeat step 1 for each of the other categories of how to send varaibles </td></tr>
  <tr><td class="indexkey"><a class="el" href="struct_rak_net_1_1_variable_list_delta_tracker_1_1_variable_last_value_node.html">RakNet::VariableListDeltaTracker::VariableLastValueNode</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_rak_net_1_1_variable_list_delta_tracker.html">RakNet::VariableListDeltaTracker</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_data_structures_1_1_weighted_graph.html">DataStructures::WeightedGraph&lt; node_type, weight_type, allow_unlinkedNodes &gt;</a></td><td class="indexvalue"></td></tr>
  <tr><td class="indexkey"><a class="el" href="class_w_s_a_startup_singleton.html">WSAStartupSingleton</a></td><td class="indexvalue"></td></tr>
</table>
</div>
<hr class="footer"/><address class="footer"><small>Generated on Thu Sep 30 2010 01:27:46 for RakNet by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img class="footer" src="doxygen.png" alt="doxygen"/></a> 1.7.1 </small></address>
</body>
</html>
